<?php
$form = $this->form;
$userRoleList = $this->userRoleList;
?>

<form
	action="<?php echo $this->url('User',['controller'=>'list','action'=>'addUser'])?>"
	method="post">
	<table>
		<tr>
			<td><label for="username">用户名</label></td><td><?php echo $this->forminput($form->get('username'));?></td></tr>
		<tr>
			<td><label for="password">密码</label></td><td><?php echo $this->forminput($form->get('password'));?></td></tr>
		
	
		
		    <td><label for="fullName">姓名</label></td><td><?php echo $this->forminput($form->get('fullName'));?></td></tr>
		
		<tr> 
		
		    <td><label for="email">邮箱</label></td><td><?php echo $this->forminput($form->get('email'));?></td></tr>
		<tr>
		    <td><label for="roleId">角色</label></td><td><select name='roleId'>
    <?php foreach ($userRoleList as $userRole) :?>
    <option  value="<?php echo $userRole->getId();?>"><?php echo $this->escapeHtml($userRole->getRoleName());?></option>
    <?php endforeach;?>
   </select></td>
		</tr>
		<tr>
		    <td><input type="submit" name="submit" value="保存" /></td>
		</tr>
		</table>
</form>


