  <?php 
        $date=$this->date;
        $programs=$this->programs;
  ?>
<div class="panel panel panel-default">
    <div class="panel-body">
       <div style="float: left;">
            <div>
                <b style="font-size: 28px;"><?php echo $playbill->getChannel()->getValue()?></b>
                <span style="margin-left: 10px"><?php echo $playbill->getProgramCount() == null?"未生成":"已生成"?></span>
            </div>
            <div style="margin-top:20px;">
                <span>提示：此节目单关联<?php echo $playbill->getProgramCount() == null?"0":$playbill->getProgramCount();?>个节目</span>
            </div>
       </div>
       <div  style="float:right;width:20%;height:100%">
  
            <?php echo "<a href=". $this->url('Program',['controller' => 'index','action' => 'edit','date' => $date,'cId'=>$playbill->getChannel()->getId()]). ">编辑节目单</a>"?>
            <?php echo "<br/>"?>
       </div>
    </div>
</div>
<table id="program" class="table table-bordered">
<tr>
<th>序号</th>
<th>节目名</th>
<th>播出时间</th>
<th>结束时间</th>
<th>类型</th>
<th>播放顺序</th>
<th>节目</th>
<th>初始名</th>
<th>重播</th>
</tr>
<?php $i=0; foreach ($programs as $program) : $i++?>
<tr>

   <td><?php echo $i;?></td>
   <td><?php echo $this->escapeHtml($program->getName());?></td>
   <td><?php echo $this->escapeHtml($program->getBroadcastTime());?></td>
   <td><?php echo $this->escapeHtml($program->getEndTime());?></td>
   <td><?php echo $this->escapeHtml($program->getType()->getValue());?></td>
   <td><?php echo $this->escapeHtml($program->getBroadcastType()->getValue());?></td>
   <td><?php echo $this->escapeHtml($program->getProgramSys()!=null?$program->getProgramSys()->getValue():"");?></td>
   <td><?php echo $this->escapeHtml($program->getInitName());?></td>
   <td><?php echo $program->getIsReplay()==true? "√":"";?></td>

</tr>
<?php endforeach; ?>
 
</table>

