<?php

$title = '登录';
$this->headTitle($title);
?>


<div class="jumbotron">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('application'));
$form->prepare();
echo $this->form()->openTag($form);
?>
    <table>
        <tr>
            <td><?php echo $this->formHidden($form->get('id'));?></td>
        </tr>
        <tr><td><?php echo $this->formRow($form->get('username'));?></td></tr>
        <tr><td><?php echo $this->formRow($form->get('password'));?></td></tr> 
        <tr><td><?php echo $this->formSubmit($form->get('submit'));?></td></tr>
    </table>
    <?php echo $this->form()->closeTag();?>
</div>


